/**
 * SEE SECTION — Rules 2-5 (expanded depth)
 * Each rule: 2,500-3,500 words with psychology, scenarios, exercises
 */
import type { Chapter } from "./types";

export const SEE_CHAPTERS_2_5: Chapter[] = [
  {
    part: "Section 1 — SEE",
    number: "Two",
    title: "Rule Two — The More You Explain Your Feelings, The Less Safe He Feels. This Is Not Your Fault. It Is His Architecture.",
    blocks: [
      { type: "p", text: "You were told to communicate your feelings. You did. It made everything worse. This is the cruelest part of the dynamic: the healthy thing — expressing yourself honestly — is also the thing that activates his retreat. And nobody told you that was what was happening." },
      { type: "p", text: "So you did the only thing you knew how to do. You tried harder. You wrote longer texts. You explained more carefully — surely, you thought, if he just understood how I feel, he would stop running. Every word was an attempt to build a bridge. Every word landed as a wall being raised on his side. The cruel arithmetic of this rule is that the more you try to connect through words, the more disconnected the other person becomes. The very tool that should work — honest communication — is the tool that, in his system, triggers the alarm." },
      { type: "quote", text: "You were told to communicate. You did. The more you explained your feelings, the less safe he felt. And nobody told you the communication was working — just not on the architecture you assumed." },
      { type: "h2", text: "The neuroscience of emotional bandwidth as threat" },
      { type: "p", text: "For someone with an avoidant pattern, emotional depth is not a gift — it is a demand. His nervous system interprets your vulnerability as an implicit ask: respond to this, match this, hold this. And that ask — even if you never said it — registers at the body level as engulfment. Research in social cognitive neuroscience found that when avoidant individuals were exposed to high-intensity emotional stimuli, the brain region that processes internal states showed decreased activation — not increased. In plain language: their brain suppresses the awareness of emotion, not amplifies it. Your words of feeling do not land in his brain as understanding opportunities. They land as threats to be suppressed." },
      { type: "p", text: "This is why the same message — I feel disconnected and it hurts — lands differently in two different nervous systems. In a secure person, it activates empathy and repair. In an avoidant person, it activates threat detection and retreat. The words are identical. The recipient architecture is different. And you have been operating as though the words were the problem, when the architecture was the variable all along." },
      { type: "h2", text: "Three real conversations that demonstrate the pattern" },
      { type: "list", items: [
        "The Vulnerability Text (sent at 11pm): A paragraph about feeling disconnected, spiraling, needing reassurance. Result: I am sorry you feel that way. I just need space sometimes. No further contact for 3 days. She was left apologizing for expressing a need. The need was not the problem. The delivery — a paragraph of vulnerability — triggered his engulfment alarm.",
        "The Long Explanation (sent the next day): A message explaining her abandonment wound, referencing past relationships, asking him to understand. Result: He read it. No reply. She waited 6 hours, then sent a follow-up. Another silence. Then: I did. I just do not know what you want me to say. She was doing the healthy thing — communicating — and it was producing the exact opposite of connection.",
        "The Corrected Version (sent after learning this rule): One sentence. I noticed distance this week and I want to talk about it when you are ready. No explanation of feelings. No reference to past wounds. Just a fact and an invitation. Result: Yeah. Let us talk tonight. Same person, same relationship, same feelings — different architecture in the message."
      ]},
      { type: "p", text: "Notice what the three messages have in common: all three express the same genuine need. The first two fail because they require him to hold emotional weight. The third succeeds because it gives him a clear, bounded, low-emotional-intensity task. The need is not the problem. The format is the architecture. And the architecture — the size and emotional weight of what you ask him to receive — is what determines whether he can stay present or must retreat." },
      { type: "h2", text: "Why you kept explaining anyway" },
      { type: "p", text: "You kept explaining because explanation was the only tool you had. You believed, with the full force of someone who loves honestly, that if he truly understood your pain, he could not keep causing it. That belief is not naive — it is the reasonable assumption of a person who assumes other people operate like she does. He does not. His withdrawal is not a failure to understand. It is a response to the pressure of being understood too closely." },
      { type: "p", text: "Here is what is actually happening on his side: emotional bandwidth registers as threat-of-engulfment in an avoidant nervous system. Your honest communication — the very thing every relationship guide told you to do — activates his escape response. Not because your feelings are wrong, and not because you are too much. Because his architecture interprets deep emotional demand as a threat to his autonomy, and his system responds the only way it knows: by creating distance. You were not communicating badly. You were communicating into a system that cannot receive the frequency you are transmitting." },
      { type: "h2", text: "The tool — Name, Not Explain Protocol" },
      { type: "p", text: "Before you send anything emotional, reduce it to one sentence naming the situation without explaining the feeling. The goal is not to suppress your feelings. The goal is to communicate in a format his architecture can receive. You will still feel everything. You just will not hand him the full emotional weight of that feeling in a single message." },
      { type: "script", when: "Before sending a long emotional text", say: "Reduce it to one sentence. Not: I have been feeling really disconnected and I do not know if something is wrong or if I am reading too much into it but when you went quiet last week I started spiraling and I just need to know where we stand. Instead: I noticed distance between us this week. Can we talk?", why: "One sentence communicates your need. Paragraphs communicate your anxiety. He can respond to a need. He shuts down at anxiety." },
      { type: "p", text: "This is not about performing detachment. It is about refusing to do the labor of over-explaining to someone who experiences your depth as pressure. Your feelings deserve to be expressed. They also deserve to be expressed in a form that can actually be received. A message that triggers his retreat does not get received. A message that names the situation and invites a conversation does. Same feelings, different delivery, radically different outcome." },
      { type: "p", text: "What this changes about the relationship: once you stop explaining your feelings in long form, something subtle happens — he stops having something to retreat from. Your short, clear messages give him no emotional weight to carry, and therefore no reason to flee. The pattern begins to break, not because he changed, but because you stopped feeding the mechanism that made his retreat necessary." },
    ],
  },
  {
    part: "Section 1 — SEE",
    number: "Three",
    title: "Rule Three — His Silence Is a Regulation Strategy. You Are Paying the Cost of His Coping.",
    blocks: [
      { type: "p", text: "You were not overreacting to his silence. You were accurately perceiving that you were being made responsible for his emotional regulation without your consent. His silence was not passive. It transferred the entire weight of the relationship's emotional state onto you. While he felt better, you fell apart. And his equilibrium was maintained on your dysregulation." },
      { type: "quote", text: "His silence was never neutral. It was never nothing. It was a transfer of emotional labor — and you were absorbing the full cost." },
      { type: "p", text: "This is the rule that makes all the other rules possible. Rule One told you that closeness is his trigger. Rule Two told you that your communication activates his retreat. Rule Three explains what happens next: he goes silent. And in that silence, the entire emotional weight of the relationship — the worry, the waiting, the checking, the spiraling — lands on you. His silence is not emptiness. It is a vacuum that fills with your anxiety. He gets relief. You get the bill." },
      { type: "h2", text: "What silence actually does — the mechanics" },
      { type: "p", text: "When an avoidant goes silent, his nervous system is doing exactly what it was designed to do: regulate itself through distance. Withdrawal works for him the way protest behavior works for you — it is a nervous-system strategy for managing overwhelm. The silence is his body answer to the question how do I survive this emotional pressure? And the answer is: disconnect, feel nothing, wait for the pressure to drop below the threshold where closeness feels safe again." },
      { type: "p", text: "The problem is not that he regulates. The problem is the asymmetry of the regulation. His silence works for him — the pressure drops, his system calms, he returns feeling neutral. But the same silence, from your side, reads as abandonment, rejection, or punishment. Your system goes into threat mode. Your body starts producing cortisol. Your mind starts writing stories: he is done, he does not care, I ruined it. Your entire nervous system is activated by the absence of connection — and his nervous system was deactivated by it. He got calm through distance. You got crisis through distance." },
      { type: "h2", text: "The silence budget — how the transfer stops" },
      { type: "p", text: "The silence budget is a behavioral boundary that stops the automatic transfer of emotional labor. It works like this: when he goes silent, you do exactly one thing — you send one check-in message. Then you stop. You do not send a second message. You do not send a follow-up. You do not check his social media. You do not call a mutual friend. You do not craft a carefully casual text that is actually desperate. You do one thing, and then you wait — not as a game, not as punishment, but as a boundary." },
      { type: "script", when: "After one unanswered message", say: "Internal rule only (not sent to him): I reached out once. I will not reach out again for 24 hours. I am not punishing him. I am stopping the labor transfer. If he wants connection, he knows where I am.", why: "The silence budget is self-regulation, not silence games. It stops the automatic filling of his silence with your anxiety. Every time you do not reach out again, you are reclaiming a piece of the emotional labor that his silence tried to transfer to you." },
      { type: "h2", text: "The three silence scenarios" },
      { type: "list", items: [
        "Scenario 1 — The 24-hour silence: He goes quiet after a close moment. Old response: three texts, two voice notes, a call, and a spiral. New response: one check-in, then silence budget. Result in most cases: he responds within 24-48 hours, often with more warmth than expected, because the absence of pursuit removed the pressure he was regulating against.",
        "Scenario 2 — The 3-day silence: He disappears entirely. Old response: catastrophic thinking, panic, reaching out to friends. New response: one check-in, then full disengagement. If 3 days pass, the silence budget resets with a second check-in. If 7 days pass, the silence is the answer — not a temporary regulation, but a withdrawal from the relationship.",
        "Scenario 3 — The ambiguous silence: He responds, but with minimal energy — k, yeah, sure. This is not silence, but it is the functional equivalent. The silence budget applies here too: one check-in, then wait. If the minimal responses continue, the pattern is telling you something about his capacity."
      ]},
      { type: "p", text: "The silence budget does not fix the relationship. It stops you from carrying the emotional weight of his coping mechanism. That is a significant change — not in what he does, but in what you absorb. And once you stop absorbing, the dynamic between you shifts." },
    ],
  },
  {
    part: "Section 1 — SEE",
    number: "Four",
    title: "Rule Four — He Comes Back After Distance and Expects Nothing to Have Changed. Because For Him, Nothing Did.",
    blocks: [
      { type: "p", text: "He came back like nothing happened. And somehow you let it slide. Again. Not because you were weak — because his re-entry felt like relief, and relief cancels clarity. There is a specific disorientation to his return: you have been living in the wreckage of his silence for days — replaying, spiraling, mourning — and then he appears, warm and ordinary, as if no time passed." },
      { type: "quote", text: "His return is not proof the pattern is fixed. It is the pattern. The relief of reconnection resets the cycle — and the cycle has an expiration date you cannot see." },
      { type: "h2", text: "For him, nothing did change" },
      { type: "p", text: "His reset is not manipulation, though it functions as manipulation. His nervous system processed the distance as resolution, not as rupture. He actually does not experience the absence as an event requiring repair. While you were drowning, he was regulating — and once he regulated, the episode was over for him. Not because he is cruel. Because his system resolved the tension the only way it knew, and moved on. Understanding this does not make it acceptable. It makes it predictable." },
      { type: "p", text: "This is the hardest part of Rule Four: the neurological explanation does not excuse the emotional cost. His system processed the silence as a reset button. Your system processed the same silence as a wound. Both are true. Both are real. But only one of them requires repair — and his system does not know that, because it did not register the damage. He comes back whole. You come back bruised. And the asymmetry is invisible to him, because his system did not keep score." },
      { type: "h2", text: "The relief-clarity inversion" },
      { type: "p", text: "When he returns, your body floods with relief — and relief is the enemy of clarity. The moment he is warm again, every boundary you rehearsed in his absence feels unnecessary. You convince yourself the peace is worth more than the conversation. But the conversation is the price of the pattern changing — and skipping it guarantees the next silence will come. Each cycle, a piece of your trust dissolves, and a piece of your self-respect goes with it. The return is not the reward. The return is the trap. Because the return teaches you that the pain of his silence will always be followed by the pleasure of his return — and that combination creates an addiction to the cycle itself." },
      { type: "p", text: "Here is what happens if you let the return slide every time: you learn that your pain has an expiration date — that if you just wait long enough, the relief will come. And once you learn that, you stop advocating for repair. You stop asking for acknowledgment. You stop requiring that the silence be addressed. You become someone who absorbs the wound and then smiles when the bandage arrives, grateful that the bleeding stopped, never asking why it started. That is not love. That is conditioning." },
      { type: "h2", text: "The tool — The Re-Entry Script" },
      { type: "p", text: "When he returns, you have words. Not accusations — conditions. The difference matters: accusations invite defensiveness; conditions invite decisions. His response tells you whether the pattern has room to change, or whether you are the only one in the relationship paying attention." },
      { type: "script", when: "When he comes back after silence as if nothing happened", say: "I want to reconnect. And I also need us to acknowledge what happened before we move forward like it did not. I am not trying to punish you. I am trying to be honest about what I need.", why: "This script does two things simultaneously: it keeps the door open (you want to reconnect) and it sets a condition (acknowledgment). It requires him to respond to both. His response to the condition tells you everything: if he engages with it, the pattern has room. If he deflects it, the pattern is fixed and you are the only one paying the price." },
      { type: "p", text: "Next time he returns, you have a framework: acknowledge what happened, set a condition for moving forward, and observe his response to the condition. If he meets it, the relationship has room to grow. If he does not, you have data — not hope, not fear, not interpretation, but behavioral evidence about his willingness to participate in repair. And data, unlike feelings, can be trusted even when it disappoints you." },
    ],
  },
  {
    part: "Section 1 — SEE",
    number: "Five",
    title: "Rule Five — You Keep Getting Blamed for Reacting to Behavior He Won't Acknowledge. That Is the Rule, Not the Exception.",
    blocks: [
      { type: "p", text: "You reacted. He made your reaction the entire story. And somewhere along the way you started to believe that story. This is the meta-rule — the one that makes all the others invisible. It works like this: he withdraws (Rule 1), you respond with distress (Rule 3's cost), and instead of the withdrawal being examined, your reaction becomes the problem. He didn't disappear — you overreacted. He didn't go cold — you're too sensitive. The spotlight swings to you, and the original behavior — his — quietly exits the conversation." },
      { type: "quote", text: "Your anxiety is not a pre-existing condition he had the bad luck to encounter. It is a predictable output of a dynamic designed to produce it." },
      { type: "h2", text: "DARVO — the psychology of blame reversal" },
      { type: "p", text: "DARVO is an acronym coined by psychologist Jennifer Freyd: Deny, Attack, Reverse Victim and Offender. It describes a specific sequence that occurs when someone is confronted with their behavior. First, the behavior is denied: I didn't disappear, I just needed space. Second, the person raising the concern is attacked: You're being dramatic or You always do this. Third, the roles are reversed: the person who caused the harm is now positioned as the victim, and the person who raised the concern is positioned as the aggressor. The entire dynamic flips, and the original behavior is never addressed." },
      { type: "p", text: "DARVO is not always conscious. In many avoidant dynamics, the person using DARVO does not know they are doing it. Their system learned this sequence early — it is a survival mechanism, not a strategy. When confronted with emotional demand, their first response is to protect themselves from the demand, and the fastest way to do that is to make the demand itself the problem." },
      { type: "h2", text: "The system that keeps you focused on yourself" },
      { type: "p", text: "The 5th Rule is the one that makes all the others work for him: the system is designed to keep you focused on your reactions and him unaccountable for his behavior. Your anxiety is not a pre-existing condition he had the bad luck to encounter. It is a predictable output of a dynamic designed to produce it. Every cycle trains you to look inward for the fault — to apologize for wanting connection, to manage your needs down to nothing, to become the quiet, easy, uncomplicated version of yourself that never disturbs the peace. That version is not peace. That version is erasure." },
      { type: "p", text: "Here is how the system works in practice: he withdraws for three days. You spiral. You send a message that is more emotional than you intended. He responds: See, this is what I'm talking about. You can't just let things be. The conversation is now about your message, not his three-day disappearance. You apologize for the message. He accepts the apology. The dynamic resets. And you are left with the understanding that your expression of pain is the problem — not his infliction of it. This is the 5th Rule in action: the behavior is invisible, the reaction is the story." },
      { type: "h2", text: "The tool — DARVO Recognition Checklist" },
      { type: "p", text: "Run this checklist the next time a conversation ends with you feeling like the problem. Each question is designed to separate what happened (behavior) from what you were told happened (interpretation). If you answer yes to three or more, you encountered DARVO — not evidence that you were too much." },
      { type: "list", items: [
        "Did I raise a legitimate concern or express a real need?",
        "Did he acknowledge it — or redirect to my tone/delivery?",
        "Did the conversation end with me apologizing?",
        "Do I feel like the problem, even though I raised the problem?",
        "Would I tell a friend she was overreacting if this happened to her?",
        "If I removed my emotional delivery entirely, would his behavior still be a concern?",
        "Am I now managing MY behavior instead of addressing HIS?"
      ]},
      { type: "p", text: "If you answered yes to three or more of these, you encountered DARVO — not evidence that you were too much. The checklist is a tool for distinguishing between two very different realities: (1) you have a communication problem, and (2) you are inside a system that uses your communication as the reason the real problem never gets addressed." },
      { type: "h2", text: "What you now know" },
      { type: "p", text: "These are the 5 Unwritten Rules. Together they form the architecture of the dynamic — the hidden mechanics that made you feel crazy, then made you feel guilty for feeling crazy. You were not crazy. You were inside a system with rules you were never told. Now you know them. That knowledge is the foundation — Section 2 gives you the calm to act on it, Section 3 gives you the words, and Section 4 gives you the decision. The rules did not change. But you did. You are no longer playing blind." },
    ],
  },
];