/**
 * CALM SECTION — Nervous System Protocol (Expanded)
 * 4 chapters: 90-Second Interrupt, Reality Anchor, Sleep Protocol, 7-Day Plan
 * Target: ~14,000 words
 */
import type { Chapter } from "./types";

export const CALM_CHAPTERS: Chapter[] = [
  {
    part: "Section 2 — CALM",
    number: "Six",
    title: "The 90-Second Interrupt",
    blocks: [
      { type: "p", text: "A regulated body is not a passive body. It is a strategic one. When you are activated, you make his job easy. A regulated woman is the most disruptive thing in this dynamic — not because she fights, but because she refuses to hand her power to the person who triggered her. This is the framing that makes everything else in this section possible: regulation is not suppression, and it is not fixing yourself. It is the opposite of what you have been doing." },
      { type: "p", text: "When you are flooded — heart pounding, mind racing, thumb hovering over send — you are operating from the survival part of your brain, and the survival brain makes terrible decisions. It sends the fifth text. It says the thing you regret. It hands your power to the person who triggered you. The 90-Second Interrupt takes that power back. Not through willpower. Not through discipline. Through a sequence that physically changes your neurochemistry in under five minutes." },
      { type: "quote", text: "You cannot out-think a nervous system in alarm. You can only change what the nervous system is doing. The Interrupt changes the chemistry, and the chemistry changes the decision." },
      { type: "h2", text: "The science in one paragraph" },
      { type: "p", text: "Jill Bolte Taylor, a neuroanatomist, proposed in her book 'My Stroke of Insight' that the chemical component of an emotion lasts approximately 90 seconds — the neurochemical cascade rises, peaks, and clears in about a minute and a half. While research shows emotion duration varies by type and context, the 90-second framework is a useful practical anchor: it tells you that what feels permanent is actually transient, and what keeps it alive is the thought loop — the replaying, the imagining, the constructing of conversations that have not happened. Your nervous system is not stuck in anxiety because the feeling is too strong. It is stuck because your mind keeps feeding it. The Interrupt breaks the loop — and the feeling, left alone, passes. The key insight is that anxiety is not a continuous state. It is a series of waves, each one re-triggered by a thought. Remove the thought, and the wave cannot restart." },
      { type: "h2", text: "The 5 Steps — in full detail" },
      { type: "p", text: "Step 1 — TIME: Look at the clock. Say the time out loud or type it into your phone notes. It is 11:47pm. This single act activates the prefrontal cortex — the rational brain — and begins interrupting the amygdala hijack that drives the spiral. Speaking or typing the time forces your brain to process factual information, which competes with the emotional processing that is driving the panic. Takes 3 seconds. Costs nothing. Works every time." },
      { type: "p", text: "Step 2 — LOCATE: Find where the feeling lives in your body. Chest tightness? Stomach knot? Jaw clenched? Throat constriction? Name it once: My chest is tight. You are not analyzing the feeling — you are locating it physically. This is not therapy-speak. Research on affect labeling shows that naming an emotion or bodily sensation reduces its intensity — it creates distance between you and the feeling, which is the first step toward managing it. When you name the location, the alarm begins to stand down." },
      { type: "p", text: "Step 3 — BREATHE: Inhale for 4 counts. Exhale for 8 counts. Repeat 4 times — not 10. Ten feels like a task, and tasks add pressure when you are already overwhelmed. Four feels like a pause. The long exhale is the critical element: it activates the vagus nerve, which runs from your brainstem to your abdomen and is the body primary parasympathetic pathway. When the vagus nerve fires, heart rate drops, blood pressure lowers, and the fight-or-flight response begins to reverse. Four rounds of 4-in/8-out takes about 90 seconds — one full emotional cycle." },
      { type: "p", text: "Step 4 — DELAY: Do not make a decision about what to send for exactly 20 minutes. Set a timer. Tell yourself: I can still do whatever I was going to do. I am giving myself 20 minutes first. The decision is not canceled — it is paused. This is critical: if you tell yourself you cannot send the message, the prohibition creates pressure (like telling yourself not to think about a white bear). If you tell yourself you CAN send it — just not yet — the pressure dissolves. After 20 minutes of regulated nervous system, the urgency that felt life-or-death will feel optional." },
      { type: "p", text: "Step 5 — GROUNDED QUESTION: After 20 minutes, ask: If I felt completely stable right now, what would I do? The answer almost never involves sending a fifth text. Usually it involves sleep, water, a shower, calling a friend, or doing nothing. The grounded question is the bridge between the emergency and the decision — it gives your regulated self the final vote, instead of your panicked self." },
      { type: "script", when: "Self-practice log — complete within 24 hours", say: "My trigger moment today was: ___. I noticed it in my: ___. I waited 20 minutes. After 20 minutes, I: ___.", why: "Completing this once converts the protocol from information to habit. One practice is worth 20 reads. The body learns through repetition, not through understanding." },
      { type: "h2", text: "Common mistakes and how to avoid them" },
      { type: "list", items: [
        "Mistake 1 — Rushing the breathe step: doing 2 quick breaths instead of 4 slow rounds. The vagus nerve needs the extended exhale to activate. Short breaths do not trigger the parasympathetic response. Slow down. The exhale must be twice the inhale.",
        "Mistake 2 — Skipping the locate step: jumping straight to breathing without naming the body sensation. The locate step is what tells the amygdala you are observing the feeling, not being consumed by it. Without it, the breathing is mechanical and less effective.",
        "Mistake 3 — Setting the delay timer but then arguing with yourself during the 20 minutes: the point of the delay is not to think about whether to send the message. The point is to let the neurochemistry shift. Distract yourself during the 20 minutes — do not deliberate.",
        "Mistake 4 — Asking the grounded question too early: if you ask it at minute 5, your nervous system is still activated and the answer will still be panic-driven. Wait the full 20 minutes. The question only works from a regulated state.",
        "Mistake 5 — Treating the Interrupt as a one-time tool: it is a practice. The first time you use it, it will feel clunky and take longer than 5 minutes. By the tenth time, it will take 90 seconds and happen automatically. Practice on small triggers — not just the relationship ones."
      ]},
      { type: "p", text: "Same script. Same silence. Different nervous system. Different result. That is the entire point of Section 2 — not to change what happens to you, but to change what happens inside you when it does." },
    ],
  },
  {
    part: "Section 2 — CALM",
    number: "Seven",
    title: "The Reality Anchor",
    blocks: [
      { type: "p", text: "He goes quiet. Within seconds, your mind is not observing the silence — it is writing a story about it. He is done with me. He hates me. I ruined it. I knew this would happen. The story feels like insight. It is not insight. It is your mind fear, wearing the costume of truth." },
      { type: "p", text: "The Reality Anchor comes from a well-researched approach called cognitive defusion, used in Acceptance and Commitment Therapy (ACT). The idea is simple: you do not have to argue with the story, and you do not have to believe it. You separate the story from the observable facts — and you anchor to the facts. The story can keep talking. You just stop letting it drive." },
      { type: "quote", text: "The Anchor sentence is not positivity. It is precision. Replace the fear story with only what is verifiably true. Precision, not positivity. That is the whole method." },
      { type: "h2", text: "The three checks — in full" },
      { type: "script", when: "When the story takes over (He is done with me / He hates me / I ruined it)", say: "Check 1 — OBSERVABLE FACT: He has not replied in 6 hours. Check 2 — KNOWN PATTERN: He goes quiet when overwhelmed. He has come back before. Check 3 — WHAT AM I ADDING: That he is done with me, that this is different, that I ruined it — these are not facts. These are fear. ANCHOR SENTENCE: He has not replied. That is all I know right now.", why: "The Anchor sentence is not positivity. It is precision. Replace the fear story with only what is verifiably true. When you strip the story down to facts, the panic has nothing to feed on — because panic runs on narrative, not on facts." },
      { type: "h2", text: "Six thought-spiral scenarios with anchors" },
      { type: "list", items: [
        "Scenario 1 — The 2am spiral: He has not replied since 6pm. Your mind constructs: He is out with someone else. He never cared. I was always second choice. ANCHOR: He has not replied in 8 hours. That is the only fact. Everything else is story.",
        "Scenario 2 — The social media check: You see he was active on Instagram but did not text back. Your mind constructs: He is choosing to ignore me. He is posting but not responding. ANCHOR: He was active on Instagram. He did not text back. These are two facts. The conclusion that he is choosing to ignore you is not a fact.",
        "Scenario 3 — The friend comparison: Your friend's boyfriend texts her every morning. Yours has not texted in two days. Your mind constructs: Normal couples do this. Something is wrong with us. ANCHOR: My boyfriend has not texted in two days. I do not know why. That is what I know.",
        "Scenario 4 — The past relationship overlay: Your ex did the same thing before breaking up. Your mind constructs: This is how it starts. He is going to leave. ANCHOR: This situation resembles a past pattern. It is not the same situation. I am not the same person. What happened before is not happening now.",
        "Scenario 5 — The self-blame: You sent a vulnerable text last week and he has been distant since. Your mind constructs: I was too much. I scared him off. ANCHOR: I sent a text. He has been distant since. Causation is not proven. Correlation is not causation.",
        "Scenario 6 — The midnight urgency: It is 1am and you need to know NOW. Your mind constructs: If I do not text now, it will be too late. ANCHOR: It is 1am. Nothing that happens at 1am is more important than what happens after sleep. I will decide in the morning."
      ]},
      { type: "h2", text: "Your Reality Anchor Card" },
      { type: "p", text: "Write your anchor sentence on a physical card. Not a note app — paper. The physical act matters: it engages procedural memory, which is more durable than digital memory. Take a photo of it and save it to your favorites. This is the version you reach for at 2am. Keep the card by your bed, and one in your bag. It belongs where the spiral happens." },
      { type: "p", text: "Rewrite it each week. The facts change; the precision stays. The card is not a mantra and it is not an affirmation. It is a fact-checker you can hold in your hand. When the story starts, you do not argue with it — you simply hold the card, and the story loses its grip, because a story cannot stand against a fact you can see." },
    ],
  },
  {
    part: "Section 2 — CALM",
    number: "Eight",
    title: "The Sleep Protocol",
    blocks: [
      { type: "p", text: "The spiral has a preferred time of day: night. The room is dark, the phone is bright, and the silence feels louder than any argument ever could. Sleep is where the pattern wins — not because you are weak at night, but because your nervous system is exhausted and your defenses are down. The Sleep Protocol is not self-care. It is strategy. A woman who sleeps is a woman who thinks clearly, and a woman who thinks clearly is the most dangerous thing to a dynamic that depends on her confusion." },
      { type: "h2", text: "The three rules — expanded" },
      { type: "p", text: "Rule 1 — The 10pm Boundary: No phone contact after 10pm when activated. Set an alarm at 9:45pm labeled BOUNDARY — no contact after this. This is a rule you make for yourself, not a rule you explain to him. The reason is neurochemical: for people experiencing chronic relational stress, normal cortisol rhythms may be disrupted — the body can remain in a state of activation when it should be winding down. Add screen light suppressing melatonin production, and you have a brain that is neurochemically impaired for clear decision-making. Every decision made after 10pm when activated is made by a compromised system. The boundary is not about him. It is about protecting your decision-making capacity from your own biology." },
      { type: "p", text: "Rule 2 — The 3-Word Sleep Anchor: Pick three words that represent who you are outside this dynamic. Not about relationships. About you. Creative, sharp, warm. Strong, funny, loyal. Quiet, observant, fierce. Write them on paper. Read them in bed. Not as affirmations — as a reminder you exist beyond this crisis. The words work because they reconnect you to an identity that is not defined by his behavior. When the spiral says you are nothing without his reply, the words say: you are these three things regardless of his reply. The identity precedes the relationship. The relationship does not create the identity." },
      { type: "p", text: "Rule 3 — The Containment Script: Write the thing you want to send. Write it fully, uncensored, every word, every emotion, no editing. Then write beneath it: I will come back to this in the morning with fresh eyes. Do not send. Put the phone face-down. You contained the impulse without suppressing the feeling. The feeling was expressed (on paper), and the behavior was stopped (phone face-down). This is the exact middle path between suppression (pretending you do not feel it) and eruption (sending it at 2am when your judgment is offline)." },
      { type: "h2", text: "Five nighttime scenarios with protocols" },
      { type: "list", items: [
        "Scenario 1 — He went quiet at 9pm and you cannot sleep: Apply the 10pm Boundary. Write the Containment Script. Read your 3-word anchor. Phone face-down. If you are still awake at 11pm, the protocol has one addition: get up, drink water, and write one sentence about what you need tomorrow (not tonight). Return to bed. The sentence converts tonight anxiety into tomorrow action.",
        "Scenario 2 — He texted something ambiguous at 8pm and you are spiraling: Do NOT respond after 10pm. Write down the exact words he sent. Write your interpretation. Write the Reality Anchor for the gap between his words and your interpretation. Save it for morning. Respond tomorrow from a regulated state.",
        "Scenario 3 — You checked his social media and saw something that triggered you: Close the app. Write what you saw. Write the story your mind constructed. Write the anchor: I saw [fact]. I constructed [story]. The fact is verifiable. The story is not. Phone face-down. The 3-word anchor. Sleep.",
        "Scenario 4 — You are in bed and the panic attack starts: Breathe first (4 in, 8 out, 4 rounds). Then locate (chest? stomach?). Then name it: This is a panic response to perceived abandonment. It is not evidence of actual abandonment. It will pass in 90 seconds if I do not feed it. Do not reach for the phone. The phone is the fuel. Without the phone, the fire has no oxygen.",
        "Scenario 5 — It is 3am and you are wide awake, mind racing: The protocol at 3am is different from 11pm. At 3am, your prefrontal cortex is offline. Do not make ANY decisions. Do not send ANY messages. Do not check ANY social media. Instead: get up, sit in a chair (not the bed — the bed is now associated with anxiety), breathe for 2 minutes, and write one sentence: Tomorrow morning I will decide. That is all you need tonight. One sentence. Then back to bed."
      ]},
      { type: "p", text: "Each rule has the same structure: the impulse is not wrong, and it is not fought — it is contained and deferred. The message gets written (the feeling is honored), the phone gets turned over (the behavior is stopped), and the morning gets a chance to arrive before the decision does. Almost nothing that feels urgent at 1am is still urgent at 9am. Sleep is the evidence." },
    ],
  },
  {
    part: "Section 2 — CALM",
    number: "Nine",
    title: "Days 1–7: Your Personal Emergency Plan",
    blocks: [
      { type: "p", text: "The next silence will come. Not because of anything you do — because patterns repeat until they are interrupted. This plan makes sure the next silence never catches you unprepared. One day at a time, one small build. Each day takes under ten minutes. What you are building over these seven days is not a new personality. It is a new reflex." },
      { type: "h2", text: "Day 1 — The Environment Setup" },
      { type: "p", text: "Your physical environment shapes your behavior more than your willpower does. Today, change the environment. Remove his contact from phone favorites — the one-tap access that makes 2am texting too easy. Set screen time limits on social media apps (15 minutes maximum). Write your Reality Anchor Card: the observable fact, the known pattern, what you are adding. Put it by your bed and in your bag. These three changes take fifteen minutes and create a physical infrastructure for the next six days." },
      { type: "h2", text: "Day 2 — The Trigger Map" },
      { type: "p", text: "Map your trigger moments. When does the panic spike? What precedes it? What time of day? What context? Write down: (1) the three times in the past month when the spiral was worst, (2) what happened immediately before each one, (3) what time it started, (4) how long it lasted. This is not therapy. This is intelligence gathering. You are building a map of your own pattern so that when the next trigger fires, you can say: I know this. I have seen this before. I know how long it lasts. The map does not prevent the trigger. It prevents the trigger from being a surprise." },
      { type: "h2", text: "Day 3 — Practice on Small Triggers" },
      { type: "p", text: "Run the 90-Second Interrupt on a SMALL trigger today — not the relationship. A work frustration. A traffic delay. A friend who cancelled. The purpose is to build the neural pathway before you need it in a high-stakes moment. When the small trigger hits: Time (say the time). Locate (where is it in your body?). Breathe (4 in, 8 out, 4 rounds). Delay (20 minutes before reacting). Grounded question (what would I do if I felt stable?). Practice once. The body learns through repetition, not through understanding." },
      { type: "h2", text: "Day 4 — The Anchor Sentence" },
      { type: "p", text: "Write your Reality Anchor sentence for the current situation. Not for the relationship in general — for right now. What is the observable fact? What is the known pattern? What are you adding? Write the anchor sentence. Photo it. Save it to your phone favorites. Read it once aloud. This sentence is your night shift — the thing that sits between you and the 2am spiral when your judgment is offline and your fear is at full volume." },
      { type: "h2", text: "Day 5 — The Sleep Protocol Trial" },
      { type: "p", text: "Run the full Sleep Protocol for one night. Set the 9:45pm alarm. Write the Containment Script if you need to. Read your 3-word anchor. Phone face-down. In the morning, evaluate: Did you sleep? Did you send the message? What happened? Write one sentence about the result. This is your data. The protocol is not magic — it is a system, and systems improve with iteration." },
      { type: "h2", text: "Day 6 — The Support Contact" },
      { type: "p", text: "Identify one person in your support network who can receive a 2am text from you instead of him. Ask them in advance: Hey, if I text you late at night about something relational, can I just vent without you fixing it? Most people will say yes. The purpose is to redirect the impulse to chase him toward a safe target. The 2am text to a friend does not damage the relationship. The 2am text to him does. Choose someone who will not judge, will not gossip, and will not tell you what to do. Just someone who will receive." },
      { type: "h2", text: "Day 7 — The Decision" },
      { type: "p", text: "Read Section 4 (The 3-Question Framework) and answer the three questions for the first time. Write them on paper. Be honest — not optimistic, not pessimistic, not hopeful. Honest. What has he consistently done? Is this improving? Where is this realistically headed? The answers will not be comfortable. Comfort was never the goal. Clarity was. After seven days of building infrastructure — environmental, neurological, behavioral, relational — you are now ready to make a decision from a regulated state instead of a panicked one. That shift is the entire book." },
      { type: "p", text: "Seven days. That is the whole plan — because the goal was never to become a different person. The goal is to walk into the next silence holding tools instead of panic. And when the tools are in your hands, the dynamic changes — because the dynamic depended on you showing up empty-handed." },
    ],
  },
];